T-4 [Yurii Leskiv] JWT login implementation
Arpha-Software/tabletop-games-shop-be pull request #11
Opened 2024-08-14 13:49 UTC by LeskivYurii

#2

2024-08-14 14:25 UTC, OleksiiDatsiuk requested changes

2024-08-14 14:25 UTC, OleksiiDatsiuk commented on common/src/main/java/org/arpha/Main.java
> +}
Do we need this class?

2024-08-14 14:25 UTC, OleksiiDatsiuk commented on common/src/main/java/org/arpha/dto/user/request/CreateUserRequest.java
> +    private String password;
Consider adding the repeatPassword field and validate it with some kind of custom jpa validation annotation

2024-08-14 14:25 UTC, OleksiiDatsiuk commented on common/src/main/java/org/arpha/dto/user/request/LoginRequest.java
> +    private String password;
So, my point of view here that we should validate this thing only in create user request

2024-08-14 14:25 UTC, OleksiiDatsiuk commented on user-service/src/main/java/org/arpha/config/FilterChainConfiguration.java
> +    private AuthJwtTokenFilter authJWTTokenFilter;
Please do not use @Autowired on fields. Consider making AuthJwtTokenFilter field private final and putting @RequiredArgsConstructor on class-level

2024-08-14 14:25 UTC, OleksiiDatsiuk commented on user-service/src/main/java/org/arpha/controller/AuthController.java
> +    }
Lets remove this enpoint when the development of this part of functionality is finished

2024-08-14 14:25 UTC, OleksiiDatsiuk commented on user-service/src/main/java/org/arpha/entity/User.java
> +@Table(name = "user", schema = "public")
Consider removing the schema value from here. What if we want to change schema at some point of time?

2024-08-15 12:45 UTC, LeskivYurii commented on common/src/main/java/org/arpha/Main.java
> +}
Deleted

2024-08-15 12:47 UTC, LeskivYurii commented on user-service/src/main/java/org/arpha/entity/User.java
> +@Table(name = "user", schema = "public")
after discussion was decided to change all entities to plural form and delete schema in annotation

2024-08-15 12:47 UTC, LeskivYurii commented on user-service/src/main/java/org/arpha/controller/AuthController.java
> +    }
Later will delete when development is finished

2024-08-15 12:48 UTC, LeskivYurii commented on user-service/src/main/java/org/arpha/config/FilterChainConfiguration.java
> +    private AuthJwtTokenFilter authJWTTokenFilter;
Fixed

2024-08-15 12:48 UTC, LeskivYurii commented on common/src/main/java/org/arpha/dto/user/request/LoginRequest.java
> +    private String password;
Deleted

2024-08-15 12:48 UTC, LeskivYurii commented on common/src/main/java/org/arpha/dto/user/request/CreateUserRequest.java
> +    private String password;
Created custom annotation @PasswordConfirmation

2024-08-15 16:12 UTC, OleksiiDatsiuk approved these changes

2024-08-16 15:42 UTC, OleksiiDatsiuk requested changes

2024-08-16 15:42 UTC, OleksiiDatsiuk commented on user-service/src/main/java/org/arpha/exception/handler/UserExceptionHandler.java
> +        return ProblemDetail.forStatusAndDetail(HttpStatus.INTERNAL_SERVER_ERROR, e.getMessage());
Consider not returning the actual error message to the user, since it can reveal some internal application information like db table names etc.

2024-08-16 16:06 UTC, OleksiiDatsiuk approved these changes

2024-08-16 16:11 UTC, merged